### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by Pastew** [tomekmucha85/sea#4]
Zrobiłem tak jak w tej instrukcji:
https://github.com/tomekmucha85/sea/pull/3
Ale nadal dostaje błąd 0xc000007b.

Co robić?

![image](https://user-images.githubusercontent.com/5671416/50993124-2758af80-1519-11e9-92a2-06fd92bd51aa.png)

**Comment by Pastew** [comment]
Budujesz 32 czy 64 bitową wersje?

**Comment by tomekmucha85** [comment]
a na konsoli jest jakiś print?
Buduję x64

**Comment by tomekmucha85** [comment]
Dodałem do repo dwa brakujące .dll oraz działającą kompilację z mojej maszyny. Wszystkie dll-e trzeba wsadzić do folderu z egzekutorem.

**Comment by Pastew** [comment]
OK, u mnie nie działało, bo nie miałem skopiowanych **wszystkich** plików .dll.
Twoje pliki .dll nie będą u mnie działać, bo ja mam nowszę wersję SDL, SDL-image oraz najnowszą wersję repo Emotiv.
Użyłem plików .dll używając  SDL, SDL-image, emotiv-sdk które sam pobrałem i opisywałem w readme, teraz wszystko działa.

W związku z powyższym proponuję wywalić wszystkie .dll z repozytorium, bo jak ktoś by chciał zrobić od nowa setup projektu, tak jak ja - to nic mu nie dadzą.
Zamiast tego poprawiłem plik readme, oto pull request:
https://github.com/tomekmucha85/sea/pull/5

**Comment by Pastew** [comment]
btw. zbudowana aplikacja którą przesłałeś też mi działa. Obie wyglądają tak samo:
![image](https://user-images.githubusercontent.com/5671416/51073502-29825180-1672-11e9-9f01-894e5f95240b.png)

**Comment by tomekmucha85** [comment]
A czy dostrzegasz problem z rozmazanym obrazem w trakcie ruchu?

**Comment by tomekmucha85** [comment]
THX. Chodziło mi właśnie o to drganie ścian. Problem zacząłem zauważać, kiedy zacząłem wyliczać ruch na zasadzie prędkość*czas. "Rozdzielczość" ruchu wzrosła wtedy na tyle, że w kolejnych klatkach położenie jakiegoś sprite'a różniło się o ~1 pixel. Wcześniej, kiedy skoki były większe, wyglądało to lepiej. Możliwe, że to normalne.
